//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Estudiantil_Universitario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docentes
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Identificacion { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Estatus { get; set; }
        public int TipoPersona { get; set; }
        public int Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Matricula { get; set; }
        public int IdProfesion { get; set; }
        public int Horario { get; set; }
    
        public virtual Profesiones Profesiones { get; set; }
    }
}
