//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Estudiantil_Universitario.Datos
{
    using System.ComponentModel.DataAnnotations;

    public partial class Horarios
    {
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "* Requerido")]
        [StringLength(50, ErrorMessage = "* No debe ser mayor a 50 caracteres")]
        public string Horario { get; set; }
    }
}
