////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace Sistema_Estudiantil_Universitario.Datos
//{
//    using DataAnnotationsExtensions;
//    using System;
//    using System.Collections.Generic;
//    using System.ComponentModel.DataAnnotations;

//    public partial class Usuarios
//    {
//        public int Id { get; set; }
//        public Nullable<System.DateTime> FechaCreacion { get; set; }
//        public Nullable<System.DateTime> FechaUltimoLogeo { get; set; }

//        [Required(AllowEmptyStrings = false, ErrorMessage = "* Requerido")]
//        [StringLength(50, MinimumLength = 4, ErrorMessage = "* Debe ser de 4 a 50 caracteres")]
//        public string Usuario { get; set; }

//        [Required(AllowEmptyStrings = false, ErrorMessage = "* Requerido")]
//        [StringLength(50, MinimumLength = 4, ErrorMessage = "* Debe ser de 4 a 50 caracteres")]
//        public string Contraseña { get; set; }

//        [Required(AllowEmptyStrings = false, ErrorMessage = "* Requerido")]
//        [EqualTo("Contraseña", ErrorMessage = "* Las contraseñas deben ser iguales")]
//        public string ConfirmarContraseña { get; set; }

//        [Required(AllowEmptyStrings = false, ErrorMessage = "* Requerido")]
//        [StringLength(50, ErrorMessage = "* No debe ser mayor a 100 caracteres")]
//        [EmailAddress(ErrorMessage = "* No valido")]
//        public string CorreoElectronico { get; set; }

//        [Required(ErrorMessage = "* Requerido")]
//        public int Estatus { get; set; }
//    }
//}


//------------------------------------------------------------------------------
// <auto-generated>
//     este código se generó a partir de una plantilla.

//     los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace sistema_estudiantil_universitario.datos
//{
//    using dataannotationsextensions;
//    using system;
//    using system.collections.generic;
//    using system.componentmodel.dataannotations;

//    public partial class profesiones
//    {
//        [system.diagnostics.codeanalysis.suppressmessage("microsoft.usage", "ca2214:donotcalloverridablemethodsinconstructors")]
//        public profesiones()
//        {
//            this.docentes = new hashset<docentes>();
//        }


//        public int id { get; set; }

//        public string codigo { get; set; }

//        [required(allowemptystrings = false, errormessage = "* requerido")]
//        [stringlength(50, minimumlength = 1, errormessage = "* debe ser mayor a 0 meses ")]
//        public string profesion { get; set; }

//        [required(allowemptystrings = false, errormessage = "* requerido")]
//        [min(1, errormessage = "* debe ser mayor a 0")]
//        public decimal duracion { get; set; }

//        [system.diagnostics.codeanalysis.suppressmessage("microsoft.usage", "ca2227:collectionpropertiesshouldbereadonly")]
//        public virtual icollection<docentes> docentes { get; set; }

//    }
//}

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace Sistema_Estudiantil_Universitario.Datos
//{
//    using System;

//    public partial class Docentes
//    {
//        public int Id { get; set; }

//        [required(allowemptystrings = false, errormessage = "* requerido")]
//        [stringlength(50, minimumlength = 1, errormessage = "* debe ser mayor a 0 meses ")]
//        public string Nombres { get; set; }

//        [required(allowemptystrings = false, errormessage = "* requerido")]
//        [stringlength(50, minimumlength = 1, errormessage = "* debe ser mayor a 0 meses ")]
//        public string Apellidos { get; set; }

//        [required(allowemptystrings = false, errormessage = "* requerido")]
//        [stringlength(50, errormessage = "* debe ser mayor a 15 caracteres")]
//        public string Identificacion { get; set; }

//        [required(allowemptystrings = false, errormessage = "* requerido")]
//        [stringlength(50, errormessage = "* debe ser mayor a 15 caracteres")]
//        public string Direccion { get; set; }
//        public string Telefono { get; set; }
//        public Nullable<int> Estatus { get; set; }
//        public int TipoDocente { get; set; }
//        public int Sexo { get; set; }
//        public System.DateTime FechaNacimiento { get; set; }
//        public Nullable<System.DateTime> FechaCreacion { get; set; }
//        public string Matricula { get; set; }
//        public int IdProfesion { get; set; }
//        public int Horario { get; set; }

//        public virtual Profesiones Profesiones { get; set; }
//    }
//}

////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace Sistema_Estudiantil_Universitario.Datos
//{
//    using System.ComponentModel.DataAnnotations;

//    public partial class Horarios
//    {
//        public int Id { get; set; }

//        [Required(AllowEmptyStrings = false, ErrorMessage = "* Requerido")]
//        [StringLength(50, ErrorMessage = "* No debe ser mayor a 50 caracteres")]
//        public string Horario { get; set; }
//    }
//}